# Generated by Django 3.2.7 on 2021-10-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='durantion',
        ),
        migrations.AddField(
            model_name='plan',
            name='total_valid_months',
            field=models.IntegerField(default=12),
        ),
    ]
